### ISSUE TITLE
macOS import of numpy gives ImportError regarding libgfortran

### ISSUE THREAD

**Issue by tengjuilin** [conda-forge/numpy-feedstock#279] opened 2022-08-19 19:08 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Installing numpy with conda-forge on macOS with

```
conda create -n numpytest numpy -c conda-forge
conda activate numpytest
python -c "import numpy"
```

gives ImportError of

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libgcc_s.1.1.dylib'
  Referenced from: '/opt/miniconda3/envs/numpytest/lib/libgfortran.5.dylib'
  Reason: tried: '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/opt/miniconda3/envs/numpytest/bin/python"
  * The NumPy version is: "1.23.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libgcc_s.1.1.dylib'
  Referenced from: '/opt/miniconda3/envs/numpytest/lib/libgfortran.5.dylib'
  Reason: tried: '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/opt/miniconda3/envs/numpytest/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)
```

This problem is previously described in https://github.com/conda-forge/numpy-feedstock/issues/126 and was solved for libgfortran 4.

The solution found in https://github.com/numpy/numpy/issues/12970 solves the problem with

```
conda uninstall numpy
conda install numpy
```

but if the environment is created with `environment.yml`, the environment will not be well-configured upon creation, which may lead to reproducibility issues.

### Installed packages

```shell
Before reinstalling numpy:
# packages in environment at /opt/miniconda3/envs/numpytest:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.6.15            h4653dfc_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcxx                    14.0.6               h04bba0f_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           11_3_0_hd922786_24    conda-forge
libgfortran5              11.3.0              hdaf2cc0_24    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libopenblas               0.3.21          openmp_hcb59c3b_1    conda-forge
libsqlite                 3.39.2               h2c9beb0_1    conda-forge
libzlib                   1.2.12               ha287fd2_2    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
numpy                     1.23.2          py310h127c7cf_0    conda-forge
openssl                   3.0.5                h7aea29f_1    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
python                    3.10.5          h4eee789_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
setuptools                65.0.2          py310hbe9552e_0    conda-forge
sqlite                    3.39.2               h40dfcc0_1    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge

After reinstalling numpy:
# packages in environment at /opt/miniconda3/envs/numpytest:
#
# Name                    Version                   Build  Channel
blas                      1.0                    openblas  
bzip2                     1.0.8                h620ffc9_4  
ca-certificates           2022.07.19           hca03da5_0  
certifi                   2022.6.15       py310hca03da5_0  
libcxx                    12.0.0               hf6beb65_1  
libffi                    3.4.2                hc377ac9_4  
libgfortran               5.0.0           11_2_0_he6877d6_26  
libgfortran5              11.2.0              he6877d6_26  
libopenblas               0.3.20               hea475bc_0  
llvm-openmp               12.0.0               haf9daa7_1  
ncurses                   6.3                  h1a28f6b_3  
numpy                     1.23.1          py310h220015d_0  
numpy-base                1.23.1          py310h742c864_0  
openssl                   1.1.1q               h1a28f6b_0  
pip                       22.1.2          py310hca03da5_0  
python                    3.10.4               hbdb9e5c_0  
readline                  8.1.2                h1a28f6b_1  
setuptools                61.2.0          py310hca03da5_0  
sqlite                    3.39.2               h1058600_0  
tk                        8.6.12               hb8d0fd4_0  
tzdata                    2022a                hda174b7_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h1a28f6b_1  
zlib                      1.2.12               h5a0b063_2
```

### Environment info

```shell
Before reinstalling numpy:
     active environment : numpytest
    active env location : /opt/miniconda3/envs/numpytest
            shell level : 1
       user config file : /Users/tlin/.condarc
 populated config files : 
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=12.5=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /Users/tlin/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /Users/tlin/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.9.12 Darwin/21.6.0 OSX/12.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False

After reinstalling numpy:

     active environment : numpytest
    active env location : /opt/miniconda3/envs/numpytest
            shell level : 1
       user config file : /Users/tlin/.condarc
 populated config files : 
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __osx=12.5=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /Users/tlin/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /Users/tlin/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.9.12 Darwin/21.6.0 OSX/12.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by isuruf** [comment] 2022-08-19 19:19
Duplicate of https://github.com/conda-forge/gfortran_impl_osx-64-feedstock/issues/54

**Closed by isuruf** 2022-08-19 19:19 UTC
Labels: bug
