### ISSUE TITLE
Different results for `np.linalg.svd` depending on numpy installation via wheel vs. via conda-forge

### ISSUE THREAD

**Issue by pavelzw** [conda-forge/numpy-feedstock#281] opened 2022-10-03 21:54 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The `np.linalg.svd` method returns different results depending on whether we install numpy with pypi or with conda-forge. 
Sorry for the non-minimal example array, all small arrays that I tested were okay :(

<details>
<summary>Details</summary>

`arr.txt`
```
7.764038654515334770e+01,3.140386545153344144e+00,-1.185961345484665586e+01,-5.917305762538964231e+00,4.627500192976873450e+01,3.638946545153341816e+00,-1.229177345484665551e+01,-1.668547845768273064e+01
7.664038654515334770e+01,-8.596134548466558556e-01,-1.285961345484665586e+01,-1.237499807023127119e+01,4.534615577592258262e+01,1.798946545153345511e+00,-1.289161345484665588e+01,-1.597616955727906962e+01
7.414038654515334770e+01,-1.859613454846655856e+00,-1.485961345484665586e+01,-6.801921147154347480e+00,4.472692500669181470e+01,1.953506545153341989e+00,-1.266713345484665609e+01,-1.729477877772556837e+01
3.514038654515334770e+01,-1.035961345484665586e+01,-1.535961345484665586e+01,-1.432115191638511753e+01,1.730384808361488425e+01,-1.098340655829493073e+01,-1.621788931691562041e+01,-1.771495936679634298e+01
3.314038654515334770e+01,-1.035961345484665586e+01,-1.535961345484665586e+01,-1.299422883946204088e+01,1.619807885284565074e+01,-1.110237207553631222e+01,-1.624564793760527692e+01,-1.779995067923057306e+01
3.214038654515334770e+01,-9.859613454846655856e+00,-1.535961345484665586e+01,-1.387884422407742591e+01,1.575577116053795734e+01,-1.108651000657079422e+01,-1.608306173070872447e+01,-1.778410459076260963e+01
9.640386545153344144e+00,-1.385961345484665586e+01,-1.635961345484665586e+01,-1.565961345484665657e+01,4.961557759225740938e-01,-1.506128012151332385e+01,-1.729611345484665463e+01,-1.782923036369738412e+01
9.640386545153344144e+00,-1.335961345484665586e+01,-1.635961345484665586e+01,-1.565961345484665657e+01,-6.096134548466558556e-01,-1.522994678817998881e+01,-1.700478012151332408e+01,-1.785961345484665586e+01
9.140386545153344144e+00,-1.385961345484665586e+01,-1.635961345484665586e+01,-1.475961345484665621e+01,-3.884596086928091552e-01,-1.521461345484665628e+01,-1.723478012151332095e+01,-1.785961345484665586e+01
-4.359613454846655856e+00,-1.635961345484665586e+01,-1.785961345484665586e+01,-1.609038268561588580e+01,-8.128844224077425906e+00,-1.674555095484665657e+01,-1.736367595484665571e+01,-1.785961345484665586e+01
-4.859613454846655856e+00,-1.585961345484665586e+01,-1.735961345484665586e+01,-1.520576730100050256e+01,-7.244228839462039105e+00,-1.678148845484665586e+01,-1.740680095484665557e+01,-1.785961345484665586e+01
-4.609613454846655856e+00,-1.535961345484665586e+01,-1.760961345484665586e+01,-1.520576730100050256e+01,-9.013459608692809155e+00,-1.743555095484665429e+01,-1.774461345484665742e+01,-1.785961345484665586e+01
-1.335961345484665586e+01,-1.705961345484665515e+01,-1.785961345484665586e+01,-1.741730576253896245e+01,-1.542692114715434926e+01,-1.720794678817998857e+01,-1.733061345484665594e+01,-1.785961345484665586e+01
-1.385961345484665586e+01,-1.705961345484665515e+01,-1.785961345484665586e+01,-1.697499807023127261e+01,-1.418845960869280987e+01,-1.745328012151332331e+01,-1.751078012151332075e+01,-1.785961345484665586e+01
-1.415961345484665657e+01,-1.735961345484665586e+01,-1.785961345484665586e+01,-1.653269037792357921e+01,-1.409999807023127083e+01,-1.752994678817998775e+01,-1.760661345484665574e+01,-1.785961345484665586e+01
-1.635961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.675192114715434855e+01,-1.772728913052233324e+01,-1.771561345484665750e+01,-1.785961345484665586e+01
-1.635961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.653038268561588708e+01,-1.792188372511692762e+01,-1.780512696836017028e+01,-1.785961345484665586e+01
-1.635961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.635315191638511578e+01,-1.750934318457638739e+01,-1.731085669808989991e+01,-1.785961345484665586e+01
5.140386545153344144e+00,3.314038654515334770e+01,7.140386545153344144e+00,7.814038654515334770e+01,1.246403865451533477e+02,5.166947745424424454e+01,2.109220472697152715e+01,1.756698596113423250e+01
5.640386545153344144e+00,4.314038654515334770e+01,1.234038654515334343e+01,1.111403865451533477e+02,1.241403865451533477e+02,4.769856836333516981e+01,2.142311381788062263e+01,1.762272979646602167e+01
4.140386545153344144e+00,4.564038654515334770e+01,1.264038654515334414e+01,1.311403865451533477e+02,1.226403865451533477e+02,4.645129563606244005e+01,2.158856836333516682e+01,1.831955424131656329e+01
-5.359613454846655856e+00,3.264038654515334770e+01,2.140386545153344144e+00,4.214038654515334770e+01,7.664038654515334770e+01,1.231181511658191496e+01,1.386838654515334568e+01,3.781248188736299198e-01
-5.359613454846655856e+00,3.314038654515334770e+01,2.640386545153344144e+00,3.414038654515334770e+01,7.564038654515334770e+01,1.265467225943906016e+01,1.362152940229620413e+01,3.885198019023370364e-01
-5.859613454846655856e+00,3.214038654515334770e+01,1.403865451533441444e-01,3.214038654515334770e+01,7.164038654515334770e+01,1.041924368801048928e+01,1.301810083086763115e+01,4.091975732980905889e-01
-1.185961345484665586e+01,1.564038654515334414e+01,-5.359613454846655856e+00,8.140386545153344144e+00,4.764038654515334770e+01,-4.101068000301198779e+00,4.120022908789703564e+00,-7.866182068298034125e+00
-1.185961345484665586e+01,1.414038654515334414e+01,-6.359613454846655856e+00,1.014038654515334414e+01,4.514038654515334770e+01,-3.826158909392111340e+00,4.355659272426070316e+00,-7.556667761701325148e+00
-1.035961345484665586e+01,1.364038654515334414e+01,-6.359613454846655856e+00,7.140386545153344144e+00,4.314038654515334770e+01,-3.721431636664839004e+00,3.943295636062433829e+00,-8.219446090829919171e+00
-1.285961345484665586e+01,5.640386545153344144e+00,-9.659613454846656566e+00,-7.172113454846655856e+00,2.010913654515334414e+01,-1.190099276519148397e+01,-2.932027247950102833e+00,-1.230256647498088540e+01
-1.235961345484665586e+01,6.140386545153344144e+00,-8.859613454846655856e+00,-7.172113454846655856e+00,1.982788654515334414e+01,-1.165271690312251707e+01,-3.260992765191481624e+00,-1.327279397060596722e+01
-1.260961345484665586e+01,5.890386545153344144e+00,-9.259613454846656211e+00,-7.172113454846655856e+00,2.067163654515334414e+01,-1.239754448932941422e+01,-4.030647937605275288e+00,-1.269666240911004351e+01
-1.735961345484665586e+01,-6.059613454846655145e+00,-1.435961345484665586e+01,-1.448461345484665586e+01,4.921636545153344144e+00,-1.509961345484665607e+01,-7.739613454846656637e+00,-1.457018007046687025e+01
-1.685961345484665586e+01,-5.559613454846655145e+00,-1.455961345484665515e+01,-1.448461345484665586e+01,5.202886545153344144e+00,-1.531294678817998900e+01,-7.919613454846656353e+00,-1.450563587876550287e+01
-1.685961345484665586e+01,-6.459613454846655500e+00,-1.435961345484665586e+01,-1.470961345484665550e+01,4.921636545153344144e+00,-1.521961345484665529e+01,-7.966280121513321433e+00,-1.450014354871744615e+01
-1.785961345484665586e+01,-1.235961345484665586e+01,-1.635961345484665586e+01,-1.617211345484665586e+01,-5.765863454846655856e+00,-1.691990757249371313e+01,-1.211549580778783231e+01,-1.612063040399919700e+01
-1.785961345484665586e+01,-1.215961345484665657e+01,-1.635961345484665586e+01,-1.617211345484665586e+01,-5.484613454846655856e+00,-1.639049580778783266e+01,-1.200299580778783159e+01,-1.633732774056094073e+01
-1.785961345484665586e+01,-1.235961345484665586e+01,-1.605961345484665515e+01,-1.560961345484665586e+01,-5.203363454846655856e+00,-1.665520169014077467e+01,-1.216181933719959574e+01,-1.594899892970699185e+01
-2.359613454846655856e+00,6.664038654515334770e+01,2.464038654515334414e+01,2.176697983098592317e+02,1.050439159569180561e+02,5.646918654515334879e+01,3.724998654515334806e+01,1.834699470054438564e+02
-3.859613454846655856e+00,9.214038654515334770e+01,2.614038654515334414e+01,1.731333277216239424e+02,9.990509242750630392e+01,5.264198654515335818e+01,3.604358654515334592e+01,1.899706906233016639e+02
-1.859613454846655856e+00,1.101403865451533477e+02,3.314038654515334770e+01,1.234580336039768724e+02,9.262509242750628857e+01,5.182038654515335452e+01,3.624118654515335436e+01,1.888194496960958020e+02
-1.185961345484665586e+01,7.314038654515334770e+01,1.514038654515334414e+01,7.157527598004278957e+01,5.994874035350716213e+01,1.394027060312436106e+01,2.291893726979102652e+01,7.074918154317997221e+01
-1.085961345484665586e+01,6.964038654515334770e+01,1.214038654515334414e+01,9.661704502181181908e+01,6.039591480068160934e+01,1.368705321182001100e+01,2.261824161761711238e+01,7.216257162340892251e+01
-1.085961345484665586e+01,6.214038654515334770e+01,1.214038654515334414e+01,9.840574281050960792e+01,5.413547254023934840e+01,1.359209669008087928e+01,2.253911118283450676e+01,7.241212688711371470e+01
-1.485961345484665586e+01,5.014038654515334770e+01,3.140386545153344144e+00,4.874863396783375435e+01,3.514554118432860719e+01,-3.046835677068878923e+00,1.142216432293112405e+01,2.647160193954383445e+01
-1.485961345484665586e+01,4.514038654515334770e+01,2.140386545153344144e+00,6.563523190597808821e+01,4.124347932865849486e+01,-2.480613454846656296e+00,1.170527543404223181e+01,2.603406299554027115e+01
-1.385961345484665586e+01,4.614038654515334770e+01,2.140386545153344144e+00,6.751152056577190308e+01,3.795997417401932239e+01,-2.298613454846655912e+00,1.131599765626445375e+01,2.626337431076828111e+01
-1.585961345484665586e+01,3.114038654515334414e+01,-4.859613454846655856e+00,1.822529220553070317e+01,1.561916013005900439e+01,-1.181620686144006172e+01,-5.513716966048995971e-01,2.467949794154673526e+00
-1.610961345484665586e+01,3.364038654515334770e+01,-2.359613454846655856e+00,1.822529220553070317e+01,1.622057522439862609e+01,-1.178818488341808468e+01,-3.412068614400602939e-01,1.037156969921763761e+00
-1.635961345484665586e+01,2.964038654515334414e+01,-4.859613454846655856e+00,1.822529220553070317e+01,1.571939597911561393e+01,-1.195631675154995222e+01,-6.167563119895156376e-01,9.338407527833325616e-02
-1.785961345484665586e+01,1.114038654515334414e+01,-9.859613454846655856e+00,-1.192946788179988005e+00,-5.679467881799880047e-01,-1.556659019903270291e+01,-5.890427408335028758e+00,-8.254372259720634375e+00
-1.685961345484665586e+01,9.140386545153344144e+00,-9.859613454846655856e+00,5.473719878486676294e+00,5.705321182001199531e-02,-1.543810182693967903e+01,-6.009032059497819489e+00,-9.194278269018242966e+00
-1.685961345484665586e+01,8.140386545153344144e+00,-9.859613454846655856e+00,-2.859613454846655856e+00,-5.679467881799880047e-01,-1.533926461763735460e+01,-5.974439036242003453e+00,-8.915436533141644304e+00
-1.785961345484665586e+01,-3.859613454846655856e+00,-1.385961345484665586e+01,-9.186144067091554177e+00,-1.005349100586706435e+01,-1.725670647810246905e+01,-1.140554368740479596e+01,-1.392755707609710747e+01
-1.785961345484665586e+01,-4.859613454846655856e+00,-1.385961345484665586e+01,-9.186144067091554177e+00,-9.619817536479310149e+00,-1.705903205949782020e+01,-1.091629950135828331e+01,-1.406220280568545888e+01
-1.785961345484665586e+01,-3.859613454846655856e+00,-1.385961345484665586e+01,-9.186144067091554177e+00,-1.048716447525481854e+01,-1.679217159438153928e+01,-1.128693903624200523e+01,-1.365876415958102541e+01
-9.359613454846655856e+00,-9.359613454846655856e+00,-5.359613454846655856e+00,-1.859613454846655856e+00,-1.635961345484665586e+01,-9.199135193977090452e+00,-3.073004759194482460e+00,8.268634372661250609e+01
-9.359613454846655856e+00,-9.359613454846655856e+00,-5.359613454846655856e+00,-4.609613454846655856e+00,-1.585961345484665586e+01,-1.070226562875970089e+01,-4.383874324411873857e+00,6.870823291227395657e+01
-1.485961345484665586e+01,-1.385961345484665586e+01,-4.859613454846655856e+00,-7.359613454846655856e+00,-1.585961345484665586e+01,-9.933222150498828285e+00,-4.597983020064045689e+00,9.813631254806334425e+01
-1.535961345484665586e+01,-1.235961345484665586e+01,-8.359613454846655856e+00,-9.859613454846655856e+00,-1.635961345484665586e+01,-1.405767949258250482e+01,-1.051647666239382595e+01,-5.905402928530868678e+00
-1.685961345484665586e+01,-1.835961345484665586e+01,-9.859613454846655856e+00,-1.085961345484665586e+01,-1.660961345484665586e+01,-1.432315119069571274e+01,-1.075350496428061753e+01,-5.291494660679020967e+00
-1.535961345484665586e+01,-1.735961345484665586e+01,-8.359613454846655856e+00,-7.859613454846655856e+00,-1.660961345484665586e+01,-1.422833986994099575e+01,-1.079617005862024115e+01,-6.021131070022805787e+00
-1.735961345484665586e+01,-1.735961345484665586e+01,-1.235961345484665586e+01,-1.085961345484665586e+01,-1.610961345484665586e+01,-1.639779527302847484e+01,-1.446545436393756390e+01,-1.611768679912689706e+01
-1.710961345484665586e+01,-1.660961345484665586e+01,-1.210961345484665586e+01,-1.085961345484665586e+01,-1.635961345484665586e+01,-1.599579527302847382e+01,-1.379393163666483701e+01,-1.504970060081615557e+01
-1.635961345484665586e+01,-1.635961345484665586e+01,-1.185961345484665586e+01,-1.085961345484665586e+01,-1.610961345484665586e+01,-1.614197709121029334e+01,-1.400406800030120102e+01,-1.483354669641582291e+01
-1.685961345484665586e+01,-1.735961345484665586e+01,-1.385961345484665586e+01,-1.485961345484665586e+01,-1.685961345484665586e+01,-1.733628012151332243e+01,-1.612214678817998958e+01,-1.644961345484665571e+01
-1.635961345484665586e+01,-1.685961345484665586e+01,-1.335961345484665586e+01,-1.485961345484665586e+01,-1.685961345484665586e+01,-1.730139123262443235e+01,-1.624076901040221088e+01,-1.637961345484665543e+01
-1.685961345484665586e+01,-1.785961345484665586e+01,-1.405961345484665515e+01,-1.585961345484665586e+01,-1.685961345484665586e+01,-1.740605789929109903e+01,-1.613610234373554420e+01,-1.655961345484665515e+01
-1.735961345484665586e+01,-1.785961345484665586e+01,-1.585961345484665586e+01,-1.785961345484665586e+01,-1.735961345484665586e+01,-1.777165956435674232e+01,-1.700646071709449458e+01,-1.720961345484665728e+01
-1.735961345484665586e+01,-1.785961345484665586e+01,-1.585961345484665586e+01,-1.785961345484665586e+01,-1.735961345484665586e+01,-1.770129645196481150e+01,-1.694489299375155511e+01,-1.730961345484665515e+01
-1.735961345484665586e+01,-1.785961345484665586e+01,-1.585961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.757816100527893255e+01,-1.683055293611466752e+01,-1.716961345484665458e+01
-1.785961345484665586e+01,-1.785961345484665586e+01,-1.735961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.775494678817998917e+01,-1.777936901040220974e+01,-1.755961345484665515e+01
-1.785961345484665586e+01,-1.785961345484665586e+01,-1.685961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.770610234373554448e+01,-1.749676901040221111e+01,-1.752961345484665756e+01
-1.785961345484665586e+01,-1.785961345484665586e+01,-1.635961345484665586e+01,-1.785961345484665586e+01,-1.785961345484665586e+01,-1.778983567706887925e+01,-1.749328012151332246e+01,-1.757961345484665472e+01
-1.465961345484665657e+01,-1.859613454846655856e+00,2.640386545153344144e+00,-2.085961345484665586e+01,-8.109613454846655856e+00,5.008346346823026352e+01,1.874500192976872981e+01,1.528744536868275716e+01
-1.515961345484665657e+01,-1.359613454846655856e+00,2.340386545153343434e+00,-2.085961345484665586e+01,-1.085961345484665586e+01,4.440807885284564804e+01,1.157807885284565330e+01,1.247922952035995792e+01
-1.565961345484665657e+01,-3.459613454846655500e+00,2.540386545153342723e+00,-2.085961345484665586e+01,-1.123461345484665586e+01,4.419269423746102632e+01,1.158884808361488084e+01,7.241290159611175170e+00
-1.600961345484665443e+01,-1.180961345484665515e+01,-3.359613454846655856e+00,-1.935961345484665586e+01,-1.473461345484665586e+01,2.716438654515333795e+01,2.017558654515334737e+01,-1.242363290379317142e+01
-1.655961345484665515e+01,-1.165961345484665657e+01,-3.659613454846656566e+00,-1.935961345484665586e+01,-1.473461345484665586e+01,2.635798654515334860e+01,1.986838654515334568e+01,-1.180961345484665515e+01
-1.585961345484665586e+01,-1.185961345484665586e+01,-4.159613454846656566e+00,-1.935961345484665586e+01,-1.460961345484665586e+01,2.635798654515333439e+01,2.007958654515334374e+01,-1.158550177971975259e+01
-1.675961345484665443e+01,-1.440961345484665657e+01,-8.059613454846655145e+00,-1.860961345484665586e+01,-1.610961345484665586e+01,2.976428211820014269e+00,1.210694904515334258e+01,-1.785961345484665586e+01
-1.705961345484665515e+01,-1.445961345484665550e+01,-8.559613454846655145e+00,-1.885961345484665586e+01,-1.610961345484665586e+01,3.620178211820014980e+00,1.308330321182000944e+01,-1.785961345484665586e+01
-1.715961345484665657e+01,-1.400961345484665621e+01,-8.259613454846656211e+00,-1.885961345484665586e+01,-1.598461345484665586e+01,4.027886545153343434e+00,1.223569904515334272e+01,-1.785961345484665586e+01
-1.744361345484665549e+01,-9.955613454846655941e+00,6.523865451533445992e-01,-1.835961345484665586e+01,-1.520961345484665550e+01,1.103303098959779049e+01,2.369401987848668156e+01,-1.577246568852363140e+01
-1.744361345484665549e+01,-1.224361345484665620e+01,-2.051613454846656026e+00,-1.835961345484665586e+01,-1.623461345484665586e+01,1.192569765626446454e+01,2.504789765626444975e+01,-1.324187882701493990e+01
-1.744361345484665549e+01,-1.245161345484665638e+01,-2.883613454846654989e+00,-1.835961345484665586e+01,-1.555961345484665515e+01,1.249105321182000949e+01,2.387255321182000856e+01,-1.609253380882895712e+01
-1.766761345484665569e+01,-1.613161345484665432e+01,-9.219613454846655287e+00,-1.810961345484665586e+01,-1.655961345484665515e+01,-1.207401345484665711e+01,-3.645213454846652823e+00,-1.785961345484665586e+01
-1.766761345484665569e+01,-1.478761345484665668e+01,-8.739613454846656637e+00,-1.810961345484665586e+01,-1.655961345484665515e+01,-1.307241345484665551e+01,-6.640413454846655128e+00,-1.785961345484665586e+01
-1.766761345484665569e+01,-1.536361345484665719e+01,-9.123613454846655202e+00,-1.810961345484665586e+01,-1.673461345484665586e+01,-1.279081345484665633e+01,-5.814813454846657237e+00,-1.785961345484665586e+01
-1.785961345484665586e+01,-1.657211345484665443e+01,-1.228044678817999014e+01,-1.785961345484665586e+01,-1.720961345484665728e+01,-1.601419678817999070e+01,-1.116461345484665557e+01,-1.785961345484665586e+01
-1.785961345484665586e+01,-1.678669678817998800e+01,-1.292419678817999085e+01,-1.785961345484665586e+01,-1.705961345484665515e+01,-1.557072456595776622e+01,-1.083558567706887743e+01,-1.785961345484665586e+01
-1.785961345484665586e+01,-1.614294678817999085e+01,-1.142211345484665586e+01,-1.785961345484665586e+01,-1.705961345484665515e+01,-1.591405789929109993e+01,-1.079266901040221072e+01,-1.785961345484665586e+01

```

</details>

Steps to reproduce:

I tested it on `osx-arm64` and 

PyPi `osx-arm64`:

```console
$ pip install numpy
[...]
$ python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.23.3 3.10.6 (main, Aug 23 2022, 09:16:05) [GCC 10.2.1 20210110]

>>> import numpy as np
>>> arr = np.loadtxt('arr.txt', delimiter=',')
>>> _, _, V = np.linalg.svd(arr)
>>> V[:, 0]
array([-0.02473903,  0.32468094, -0.7769144 ,  0.44309233, -0.19122197,
        0.11624773, -0.01711495, -0.20897646])
```

PyPi `linux-64`:

```console
$ pip install numpy
[...]
$ python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.23.3 3.10.6 (main, Aug 23 2022, 08:25:41) [GCC 10.2.1 20210110]

>>> import numpy as np
>>> arr = np.loadtxt('arr.txt', delimiter=',')
>>> _, _, V = np.linalg.svd(arr)
>>> V[:, 0]
array([-0.02473903,  0.32468094, -0.7769144 ,  0.44309233, -0.19122197,
        0.11624773, -0.01711495, -0.20897646])
```

Conda-forge `osx-arm64`:

```console
$ micromamba install -c conda-forge numpy
[...]
$ micromamba list
[...]
  numpy                  1.23.3     py310he617cf3_0           conda-forge
[...]

$ python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.23.3 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:27:42) [GCC 10.4.0]

>>> import numpy as np
>>> arr = np.loadtxt('arr.txt', delimiter=',')
>>> _, _, V = np.linalg.svd(arr)
>>> V[:, 0]
array([-0.02473903,  0.32468094, -0.7769144 ,  0.44309233, -0.19122197,
       -0.11624773,  0.01711495, -0.20897646])
```

Conda-forge `linux-64`:

```console
$ micromamba install -c conda-forge numpy
[...]
$ micromamba list
[...]
  numpy             1.23.3     py310h53a5b5f_0      conda-forge
[...]

$ python
>>> import sys, numpy; print(numpy.__version__, sys.version)
1.23.3 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:36:39) [GCC 10.4.0]

>>> import numpy as np
>>> arr = np.loadtxt('arr.txt', delimiter=',')
>>> _, _, V = np.linalg.svd(arr)
>>> V[:, 0]
array([-0.02473903,  0.32468094, -0.7769144 ,  0.44309233, -0.19122197,
       -0.11624773,  0.01711495, -0.20897646])
```

As we can see here, the sign of `V[5, 0]` and `V[6, 0]` is different between the conda-forge build and the wheel build.

### Installed packages

```shell
Name                   Version    Build                     Channel
───────────────────────────────────────────────────────────────────────────
  _openmp_mutex          4.5        2_gnu                     conda-forge
  bzip2                  1.0.8      hf897c2e_4                conda-forge
  ca-certificates        2022.9.24  h4fd8a4c_0                conda-forge
  ld_impl_linux-aarch64  2.36.1     h02ad14f_2                conda-forge
  libblas                3.9.0      16_linuxaarch64_openblas  conda-forge
  libcblas               3.9.0      16_linuxaarch64_openblas  conda-forge
  libffi                 3.4.2      h3557bc0_5                conda-forge
  libgcc-ng              12.1.0     h3242a24_16               conda-forge
  libgfortran-ng         12.1.0     he9431aa_16               conda-forge
  libgfortran5           12.1.0     h41d5c85_16               conda-forge
  libgomp                12.1.0     h3242a24_16               conda-forge
  liblapack              3.9.0      16_linuxaarch64_openblas  conda-forge
  libnsl                 2.0.0      hf897c2e_0                conda-forge
  libopenblas            0.3.21     pthreads_h6cb6f83_3       conda-forge
  libsqlite              3.39.4     hf9034f9_0                conda-forge
  libstdcxx-ng           12.1.0     hd01590b_16               conda-forge
  libuuid                2.32.1     hf897c2e_1000             conda-forge
  libzlib                1.2.12     h4e544f5_4                conda-forge
  ncurses                6.3        headf329_1                conda-forge
  numpy                  1.23.3     py310he617cf3_0           conda-forge
  openssl                3.0.5      h4e544f5_2                conda-forge
  pip                    22.2.2     pyhd8ed1ab_0              conda-forge
  python                 3.10.6     h92ab765_0_cpython        conda-forge
  python_abi             3.10       2_cp310                   conda-forge
  readline               8.1.2      h38e3740_0                conda-forge
  setuptools             65.4.1     pyhd8ed1ab_0              conda-forge
  tk                     8.6.12     hd8af866_0                conda-forge
  tzdata                 2022d      h191b570_0                conda-forge
  wheel                  0.37.1     pyhd8ed1ab_0              conda-forge
  xz                     5.2.6      h9cdd2b7_0                conda-forge
```

### Environment info

```shell
__
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/


            environment : base (active)
           env location : /opt/conda
      user config files : /home/mambauser/.mambarc
 populated config files :
       libmamba version : 0.24.0
     micromamba version : 0.24.0
           curl version : libcurl/7.83.1 OpenSSL/1.1.1o zlib/1.2.12 libssh2/1.10.0 nghttp2/1.47.0
     libarchive version : libarchive 3.3.3 zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.2 libzstd/1.4.5
       virtual packages : __unix=0=0
                          __linux=5.10.124=0
                          __glibc=2.31=0
                          __archspec=1=aarch64
               channels :
       base environment : /opt/conda
               platform : linux-aarch64
```

**Comment by rgommers** [comment] 2022-10-03 22:08
That is completely expected, decompositions like SVD may give different numerical results for different BLAS/LAPACK libraries, or on different platforms. The only thing you can count on is that the decomposition is valid (i.e. you can reconstruct the input array from the returned `s`, `v` and `d` values.

I will close this, as it is not a bug.

**Closed by rgommers** 2022-10-03 22:08 UTC
Labels: bug
