### ISSUE TITLE
Numpy conda package broken inside tox on Windows, Python 3.7/3.8

### ISSUE THREAD

**Issue by goerz** [conda-forge/numpy-feedstock#184] opened 2020-02-07 23:46 UTC
The conda-package for numpy does not work on Windows inside a tox environment. See cross-reference https://github.com/numpy/numpy/issues/15537

**Comment by jan-janssen** [comment] 2021-02-01 14:16
I tried to trigger a new build - hopefully that is sufficient https://github.com/conda-forge/numpy-feedstock/pull/224

**Comment by jan-janssen** [comment] 2021-02-01 17:00
For me the issue seems to be fixed now.

**Closed** 2021-02-02 14:53 UTC

**Comment by jakirkham** [comment] 2021-02-02 14:54
Thanks for the update. Let’s go ahead and close then

**Comment by basnijholt** [comment] 2021-02-26 14:23
I still see the issue described by @goerz  in the upstream issue https://github.com/numpy/numpy/issues/15537 for v1.20.1:
```
E   ImportError: 
E   
E   IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
E   
E   Importing the numpy C-extensions failed. This error can happen for
E   many reasons, often due to issues with your setup or how NumPy was
E   installed.
E   
E   We have compiled some common reasons and troubleshooting tips at:
E   
E       https://numpy.org/devdocs/user/troubleshooting-importerror.html
E   
E   Please note and check the following:
E   
E     * The Python version is: Python3.8 from "d:\a\1\s\.tox\py38\python.exe"
E     * The NumPy version is: "1.20.1"
E   
E   and make sure that they are the versions you expect.
E   Please carefully study the documentation linked above for further help.
E   
E   Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
```

**Comment by rgommers** [comment] 2021-02-26 14:45
So did you activate your conda environment, like the solution https://github.com/numpy/numpy/issues/15537#issuecomment-583773970 says?

**Comment by basnijholt** [comment] 2021-02-26 15:03
Unfortunately, I am not in control of that. It happens for me when using Tox with `tox-conda` in our CI.

The related issue is https://github.com/tox-dev/tox-conda/issues/37

**Comment by jakirkham** [comment] 2021-02-26 16:05
It would be good if someone could reproduce the issue without tox. If that's not possible, it may simply be a tox issue

**Comment by basnijholt** [comment] 2021-02-26 16:11
I don't have access to a Windows machine :(

However, the following might give someone with more knowledge than me some clues.

Using `set CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1` while using `numpy` from the `defaults` channel fixed the issue. The [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed) describe what this does, however, there it's the solution to a (seemly?) different problem.
